from __future__ import annotations

"""Checkpoint evaluation, BEM reconstruction, metrics, and publication-oriented visualization."""


import argparse
import json
from pathlib import Path
from typing import Any, Callable

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import torch
from matplotlib.lines import Line2D
from matplotlib.ticker import FixedFormatter, FixedLocator

from bem_solver import (
    BEMCache,
    evaluate_field,
    solve_flux_collocation_cached,
)
from dataset import BoundaryFluxDataset
from geometry import make_domain_quadrature
from model import FluxGNN


# =========================================================
# Global font configuration
# =========================================================

mpl.rcParams["font.family"] = "serif"
mpl.rcParams["font.serif"] = [
    "Times New Roman",
    "Times",
    "DejaVu Serif",
]
mpl.rcParams["mathtext.fontset"] = "stix"
mpl.rcParams["axes.unicode_minus"] = False


# =========================================================
# Default configuration
# =========================================================

DEFAULT_CONFIG = {
    "data_dir": "data/case3",
    "case": "case3",

    # Use the checkpoint generated by the new attention model.
    "ckpt": "runs/case3_full_attention/best.pt",

    "out_dir": "results/case3_full_attention",
    "sample_idx": 0,
    "quad_res": 121,
}


# =========================================================
# Global plotting configuration
# =========================================================

PLOT_CFG = {
    "figsize_main": (21.0, 12.0),
    "figsize_extra": (14.0, 6.0),
    "dpi_png": 900,

    "boundary_marker_size": 34,
    "interior_marker_size": 18,
    "unknown_x_size": 28,
    "unknown_x_linewidth": 1.2,

    "legend_fontsize": 23,
    "title_fontsize": 23,
    "suptitle_fontsize": 13,
    "label_fontsize": 27,
    "tick_labelsize": 21,
    "axis_linewidth": 0.8,

    "show_legend": False,
    "show_grid": False,
    "grid_alpha": 0.25,

    "x_label": "x",
    "y_label": "y",

    "colorbar_fraction": 0.050,
    "colorbar_pad": 0.020,
    "colorbar_shrink": 1.0,
    "colorbar_aspect": 28,
    "colorbar_ticksize": 13,
    "colorbar_n_ticks": 7,

    "known_edgecolor": "k",
    "unknown_color": "red",
    "unknown_label": "Unknown or highlighted",

    "cmap_u": "viridis",
    "cmap_q": "coolwarm",
    "cmap_err": "coolwarm",
}


# =========================================================
# Per-subplot configuration
# =========================================================

SUBPLOT_CFG = {
    "known_u": {
        "title": "Known Boundary Dirichlet Data",
        "legend_label": "Known Boundary Dirichlet Data",
        "legend_loc": "upper right",
        "cmap": PLOT_CFG["cmap_u"],
        "show_red_x": False,
        "x_mode": "none",
        "show_colorbar": True,
    },
    "pred_q": {
        "title": "Predicted Neumann Data",
        "legend_label": "Predicted Neumann Data",
        "legend_loc": "upper right",
        "cmap": PLOT_CFG["cmap_q"],
        "show_red_x": False,
        "x_mode": "left_right",
        "show_colorbar": True,
    },
    "true_q": {
        "title": "Exact Neumann Data",
        "legend_label": "Exact Neumann Data",
        "legend_loc": "upper right",
        "cmap": PLOT_CFG["cmap_q"],
        "show_red_x": False,
        "x_mode": "left_right",
        "show_colorbar": True,
    },
    "pred_u": {
        "title": "Interior Field from Predicted Boundary Data",
        "legend_label": "Predicted Interior Field",
        "legend_loc": "upper right",
        "cmap": PLOT_CFG["cmap_u"],
        "show_red_x": False,
        "x_mode": "none",
        "show_colorbar": True,
    },
    "true_u": {
        "title": "Exact Interior Field",
        "legend_label": "Exact Interior Field",
        "legend_loc": "upper right",
        "cmap": PLOT_CFG["cmap_u"],
        "show_red_x": False,
        "x_mode": "none",
        "show_colorbar": True,
    },
    "u_err": {
        "title": "Interior Field Error",
        "legend_label": "Interior Field Error",
        "legend_loc": "upper right",
        "cmap": PLOT_CFG["cmap_err"],
        "show_red_x": False,
        "x_mode": "none",
        "show_colorbar": True,
    },
    "q_err": {
        "title": "Boundary Neumann Error",
        "legend_label": "Boundary Neumann Error",
        "legend_loc": "upper right",
        "cmap": PLOT_CFG["cmap_err"],
        "show_red_x": False,
        "x_mode": "large_q_error",
        "show_colorbar": True,
    },
    "bem_u": {
        "title": "Interior Field from BEM-Solved Neumann Data",
        "legend_label": "BEM Interior Field",
        "legend_loc": "upper right",
        "cmap": PLOT_CFG["cmap_u"],
        "show_red_x": False,
        "x_mode": "none",
        "show_colorbar": True,
    },
}


X_CFG = {
    "large_error_threshold_q": 0.03,
    "large_error_threshold_u": 0.03,
}


# =========================================================
# Forced axis tick/range configuration
# =========================================================

AXIS_TICK_CFG = {
    "case1": {
        "enable": False,
    },
    "case2": {
        "enable": True,
        "xlim": (-1.40, 1.40),
        "ylim": (-1.40, 1.40),

        "x_start": -1.25,
        "y_start": -1.25,
        "x_step": 0.50,
        "y_step": 0.50,
        "x_count": 6,
        "y_count": 6,
        "label_fmt": "{:.2f}",
    },
    "case3": {
        "enable": True,
        "xlim": (-0.20, 1.20),
        "ylim": (-0.20, 1.20),

        # Standard unit-square ticks: 0.0, 0.2, ..., 1.0.
        "x_start": 0.0,
        "y_start": 0.0,
        "x_step": 0.2,
        "y_step": 0.2,
        "x_count": 6,
        "y_count": 6,
        "label_fmt": "{:.1f}",
    },
}


# =========================================================
# Array and validation utilities
# =========================================================

def _to_numpy(
    value: Any,
    *,
    dtype: np.dtype | type | None = None,
    flatten: bool = False,
) -> np.ndarray:
    """
    Convert a PyTorch tensor or array-like object to a NumPy array.
    """
    if isinstance(value, torch.Tensor):
        array = value.detach().cpu().numpy()
    else:
        array = np.asarray(value)

    if dtype is not None:
        array = array.astype(dtype, copy=False)

    if flatten:
        array = array.reshape(-1)

    return array


def _check_finite(
    name: str,
    array: np.ndarray,
    *,
    allow_nan: bool = False,
) -> None:
    """
    Validate that an array does not contain invalid numerical values.
    """
    array = np.asarray(array)

    if allow_nan:
        if np.any(np.isinf(array)):
            raise FloatingPointError(
                f"{name} contains infinite values"
            )
    else:
        if not np.all(np.isfinite(array)):
            raise FloatingPointError(
                f"{name} contains NaN or infinite values"
            )


def _validate_same_shape(
    name_a: str,
    array_a: np.ndarray,
    name_b: str,
    array_b: np.ndarray,
) -> None:
    if array_a.shape != array_b.shape:
        raise ValueError(
            f"{name_a} shape {array_a.shape} does not match "
            f"{name_b} shape {array_b.shape}"
        )


def _finite_minmax(
    *arrays: np.ndarray,
    padding: float = 1e-8,
) -> tuple[float, float]:
    """
    Return a common finite minimum and maximum for multiple arrays.
    """
    finite_parts: list[np.ndarray] = []

    for array in arrays:
        values = np.asarray(array, dtype=np.float64)
        finite_values = values[np.isfinite(values)]

        if finite_values.size > 0:
            finite_parts.append(finite_values)

    if not finite_parts:
        raise ValueError(
            "Cannot determine a color range from empty or non-finite arrays"
        )

    combined = np.concatenate(finite_parts)

    vmin = float(np.min(combined))
    vmax = float(np.max(combined))

    if np.isclose(vmin, vmax):
        scale = max(abs(vmin), 1.0)
        delta = max(padding, padding * scale)

        vmin -= delta
        vmax += delta

    return vmin, vmax


def _symmetric_limit(
    array: np.ndarray,
    *,
    minimum: float = 1e-12,
) -> float:
    """
    Return a positive symmetric color limit around zero.
    """
    values = np.asarray(array, dtype=np.float64)
    finite_values = values[np.isfinite(values)]

    if finite_values.size == 0:
        return minimum

    limit = float(np.max(np.abs(finite_values)))

    if not np.isfinite(limit) or limit < minimum:
        limit = minimum

    return limit


def _validate_node_array(
    name: str,
    array: np.ndarray,
    num_nodes: int,
) -> np.ndarray:
    """
    Flatten and validate a node-wise array.
    """
    array = np.asarray(array, dtype=np.float64).reshape(-1)

    if array.shape[0] != num_nodes:
        raise ValueError(
            f"{name} contains {array.shape[0]} values, "
            f"but the boundary has {num_nodes} nodes"
        )

    _check_finite(name, array)

    return array


# =========================================================
# Problem definitions
# =========================================================

def build_problem_from_params(
    case: str,
    params: np.ndarray,
) -> Callable[[np.ndarray], np.ndarray]:
    """
    Construct the source-term function for the selected problem.
    """
    params = np.asarray(params, dtype=np.float64).reshape(-1)

    if case == "case1":
        # Case 1 is the Laplace equation:
        #     -Delta u = 0.
        def f_fn(x: np.ndarray) -> np.ndarray:
            x = np.asarray(x)

            return np.zeros(
                (x.shape[0],),
                dtype=np.float64,
            )

        return f_fn

    if case == "case2":
        if params.size < 3:
            raise ValueError(
                "case2 requires at least three parameters: [a, b, c]"
            )

        a, b, c = [float(v) for v in params[:3]]

        def f_fn(x: np.ndarray) -> np.ndarray:
            x = np.asarray(x, dtype=np.float64)

            xx = x[:, 0]
            yy = x[:, 1]

            return (
                4.0 * a
                + 8.0 * b * xx
                + 8.0 * c * yy
            )

        return f_fn

    if case == "case3":
        if params.size < 3:
            raise ValueError(
                "case3 requires at least three parameters: [A, m, n]"
            )

        amplitude = float(params[0])
        frequency_m = int(round(float(params[1])))
        frequency_n = int(round(float(params[2])))

        def f_fn(x: np.ndarray) -> np.ndarray:
            x = np.asarray(x, dtype=np.float64)

            xx = x[:, 0]
            yy = x[:, 1]

            factor = (
                amplitude
                * np.pi**2
                * (
                    frequency_m**2
                    + frequency_n**2
                )
            )

            return (
                factor
                * np.sin(frequency_m * np.pi * xx)
                * np.sin(frequency_n * np.pi * yy)
            )

        return f_fn

    raise ValueError(
        f"Unknown case '{case}'. "
        "Expected one of: case1, case2, case3"
    )


# =========================================================
# Metric utilities
# =========================================================

def compute_error_metrics(
    prediction: np.ndarray,
    reference: np.ndarray,
) -> dict[str, float]:
    """
    Compute common regression error metrics.
    """
    prediction = np.asarray(
        prediction,
        dtype=np.float64,
    ).reshape(-1)

    reference = np.asarray(
        reference,
        dtype=np.float64,
    ).reshape(-1)

    _validate_same_shape(
        "prediction",
        prediction,
        "reference",
        reference,
    )

    valid = (
        np.isfinite(prediction)
        & np.isfinite(reference)
    )

    if not np.any(valid):
        raise ValueError(
            "No finite prediction-reference pairs are available"
        )

    prediction_valid = prediction[valid]
    reference_valid = reference[valid]

    error = prediction_valid - reference_valid

    mse = float(np.mean(error**2))
    rmse = float(np.sqrt(mse))
    mae = float(np.mean(np.abs(error)))
    max_abs = float(np.max(np.abs(error)))

    reference_norm = float(
        np.linalg.norm(reference_valid)
    )

    error_norm = float(
        np.linalg.norm(error)
    )

    if reference_norm > 1e-14:
        relative_l2 = error_norm / reference_norm
    else:
        relative_l2 = float("nan")

    reference_range = float(
        np.max(reference_valid)
        - np.min(reference_valid)
    )

    if reference_range > 1e-14:
        normalized_max_abs = max_abs / reference_range
    else:
        normalized_max_abs = float("nan")

    return {
        "mse": mse,
        "rmse": rmse,
        "mae": mae,
        "max_abs": max_abs,
        "relative_l2": float(relative_l2),
        "normalized_max_abs": float(normalized_max_abs),
    }


# =========================================================
# Axis and style utilities
# =========================================================

def _build_forced_ticks(
    start: float,
    step: float,
    count: int,
) -> np.ndarray:
    if count <= 0:
        raise ValueError("count must be greater than zero")

    return (
        start
        + step
        * np.arange(count, dtype=np.float64)
    )


def _apply_forced_ticks(
    ax: mpl.axes.Axes,
    case: str | None,
) -> None:
    if case is None:
        return

    cfg = AXIS_TICK_CFG.get(
        case,
        {"enable": False},
    )

    if not cfg.get("enable", False):
        return

    xticks = _build_forced_ticks(
        cfg["x_start"],
        cfg["x_step"],
        cfg["x_count"],
    )

    yticks = _build_forced_ticks(
        cfg["y_start"],
        cfg["y_step"],
        cfg["y_count"],
    )

    xlabels = [
        cfg["label_fmt"].format(value)
        for value in xticks
    ]

    ylabels = [
        cfg["label_fmt"].format(value)
        for value in yticks
    ]

    ax.xaxis.set_major_locator(
        FixedLocator(xticks)
    )

    ax.yaxis.set_major_locator(
        FixedLocator(yticks)
    )

    ax.xaxis.set_major_formatter(
        FixedFormatter(xlabels)
    )

    ax.yaxis.set_major_formatter(
        FixedFormatter(ylabels)
    )

    ax.set_xlim(*cfg["xlim"])
    ax.set_ylim(*cfg["ylim"])
    ax.minorticks_off()


def _apply_axis_style(
    ax: mpl.axes.Axes,
    case: str | None = None,
) -> None:
    ax.set_xlabel(
        PLOT_CFG["x_label"],
        fontsize=PLOT_CFG["label_fontsize"],
        fontstyle="italic",
    )

    ax.set_ylabel(
        PLOT_CFG["y_label"],
        fontsize=PLOT_CFG["label_fontsize"],
        fontstyle="italic",
    )

    ax.tick_params(
        axis="both",
        labelsize=PLOT_CFG["tick_labelsize"],
        width=PLOT_CFG["axis_linewidth"],
    )

    for spine in ax.spines.values():
        spine.set_linewidth(
            PLOT_CFG["axis_linewidth"]
        )

    if PLOT_CFG["show_grid"]:
        ax.grid(
            True,
            alpha=PLOT_CFG["grid_alpha"],
        )

    _apply_forced_ticks(
        ax,
        case,
    )


def _make_legend(
    ax: mpl.axes.Axes,
    label: str | None = None,
    add_unknown: bool = False,
    legend_loc: str = "upper right",
) -> None:
    if not PLOT_CFG.get("show_legend", True):
        return

    handles: list[Line2D] = []

    if label is not None:
        handles.append(
            Line2D(
                [0],
                [0],
                marker="o",
                color="w",
                label=label,
                markerfacecolor="gray",
                markeredgecolor=PLOT_CFG["known_edgecolor"],
                markersize=6,
            )
        )

    if add_unknown:
        handles.append(
            Line2D(
                [0],
                [0],
                marker="x",
                color=PLOT_CFG["unknown_color"],
                label=PLOT_CFG["unknown_label"],
                linestyle="None",
                markersize=7,
                markeredgewidth=1.2,
            )
        )

    if handles:
        ax.legend(
            handles=handles,
            loc=legend_loc,
            fontsize=PLOT_CFG["legend_fontsize"],
            frameon=True,
        )


def _add_colorbar(
    fig: mpl.figure.Figure,
    ax: mpl.axes.Axes,
    artist: Any,
    fmt: str | None = None,
):
    vmin, vmax = artist.get_clim()

    n_ticks = int(
        PLOT_CFG.get("colorbar_n_ticks", 7)
    )

    if np.isclose(vmin, vmax):
        ticks = [vmin]
    else:
        ticks = np.linspace(
            vmin,
            vmax,
            n_ticks,
        )

    colorbar = fig.colorbar(
        artist,
        ax=ax,
        fraction=PLOT_CFG["colorbar_fraction"],
        pad=PLOT_CFG["colorbar_pad"],
        shrink=PLOT_CFG["colorbar_shrink"],
        aspect=PLOT_CFG["colorbar_aspect"],
        format=fmt,
        ticks=ticks,
    )

    colorbar.ax.tick_params(
        labelsize=PLOT_CFG["colorbar_ticksize"]
    )

    return colorbar


# =========================================================
# Highlight-mask utilities
# =========================================================

def _boundary_edge_masks(
    coords_np: np.ndarray,
    tol: float = 1e-8,
) -> dict[str, np.ndarray]:
    coords_np = np.asarray(
        coords_np,
        dtype=np.float64,
    )

    if coords_np.ndim != 2 or coords_np.shape[1] != 2:
        raise ValueError(
            "Boundary coordinates must have shape [N, 2]"
        )

    x = coords_np[:, 0]
    y = coords_np[:, 1]

    x_min = float(np.min(x))
    x_max = float(np.max(x))
    y_min = float(np.min(y))
    y_max = float(np.max(y))

    left = np.abs(x - x_min) < tol
    right = np.abs(x - x_max) < tol
    bottom = np.abs(y - y_min) < tol
    top = np.abs(y - y_max) < tol

    return {
        "left": left,
        "right": right,
        "top": top,
        "bottom": bottom,
        "left_right": left | right,
        "top_bottom": top | bottom,
        "all_boundary": (
            left
            | right
            | top
            | bottom
        ),
    }


def build_custom_masks(
    boundary_coords: np.ndarray,
    q_err: np.ndarray | None = None,
    u_err_grid: np.ndarray | None = None,
) -> dict[str, np.ndarray]:
    custom_masks: dict[str, np.ndarray] = {}

    # Examples:
    #
    # custom_masks["left_half"] = (
    #     boundary_coords[:, 0] < 0.5
    # )
    #
    # if q_err is not None:
    #     custom_masks["positive_q_error"] = q_err > 0.0
    #
    # if u_err_grid is not None:
    #     custom_masks["large_u_region"] = (
    #         np.abs(u_err_grid) > 0.05
    #     )

    return custom_masks


def build_boundary_x_mask(
    mode: str | None,
    boundary_coords: np.ndarray,
    q_err: np.ndarray | None = None,
) -> np.ndarray | None:
    if mode is None or mode == "none":
        return None

    edges = _boundary_edge_masks(
        boundary_coords
    )

    custom = build_custom_masks(
        boundary_coords,
        q_err=q_err,
        u_err_grid=None,
    )

    if mode in edges:
        return edges[mode]

    if mode == "large_q_error":
        if q_err is None:
            raise ValueError(
                "large_q_error mode requires q_err"
            )

        return (
            np.abs(q_err)
            > X_CFG["large_error_threshold_q"]
        )

    if mode in custom:
        return custom[mode]

    raise ValueError(
        f"Unknown boundary x_mode: {mode}"
    )


def build_grid_x_mask(
    mode: str | None,
    boundary_coords: np.ndarray,
    u_err_grid: np.ndarray | None = None,
) -> np.ndarray | None:
    if mode is None or mode == "none":
        return None

    custom = build_custom_masks(
        boundary_coords,
        q_err=None,
        u_err_grid=u_err_grid,
    )

    if mode == "large_u_error":
        if u_err_grid is None:
            raise ValueError(
                "large_u_error mode requires u_err_grid"
            )

        return (
            np.abs(u_err_grid)
            > X_CFG["large_error_threshold_u"]
        )

    if mode in custom:
        return custom[mode]

    raise ValueError(
        f"Unknown grid x_mode: {mode}"
    )


def build_interior_x_mask(
    mode: str | None,
    u_err: np.ndarray | None = None,
) -> np.ndarray | None:
    if mode is None or mode == "none":
        return None

    if mode == "large_u_error":
        if u_err is None:
            raise ValueError(
                "large_u_error mode requires u_err"
            )

        return (
            np.abs(u_err)
            > X_CFG["large_error_threshold_u"]
        )

    raise ValueError(
        f"Unknown interior x_mode: {mode}"
    )


# =========================================================
# Plotting utilities
# =========================================================

def _scatter_boundary(
    fig: mpl.figure.Figure,
    ax: mpl.axes.Axes,
    coords: np.ndarray,
    values: np.ndarray,
    cfg: dict[str, Any],
    x_mask: np.ndarray | None = None,
    vmin: float | None = None,
    vmax: float | None = None,
    cbar_fmt: str | None = None,
    case: str | None = None,
) -> None:
    coords = np.asarray(
        coords,
        dtype=np.float64,
    )

    values = np.asarray(
        values,
        dtype=np.float64,
    ).reshape(-1)

    if coords.shape[0] != values.shape[0]:
        raise ValueError(
            "Boundary coordinates and values have different lengths"
        )

    scatter = ax.scatter(
        coords[:, 0],
        coords[:, 1],
        c=values,
        s=PLOT_CFG["boundary_marker_size"],
        cmap=cfg["cmap"],
        vmin=vmin,
        vmax=vmax,
        edgecolors=PLOT_CFG["known_edgecolor"],
        linewidths=0.25,
    )

    if cfg.get("show_colorbar", True):
        _add_colorbar(
            fig,
            ax,
            scatter,
            fmt=cbar_fmt,
        )

    add_unknown = False

    if (
        cfg.get("show_red_x", True)
        and x_mask is not None
        and np.any(x_mask)
    ):
        x_mask = np.asarray(
            x_mask,
            dtype=bool,
        ).reshape(-1)

        if x_mask.shape[0] != coords.shape[0]:
            raise ValueError(
                "Boundary highlight mask has an invalid length"
            )

        add_unknown = True

        ax.scatter(
            coords[x_mask, 0],
            coords[x_mask, 1],
            s=PLOT_CFG["unknown_x_size"],
            c=PLOT_CFG["unknown_color"],
            marker="x",
            linewidths=PLOT_CFG["unknown_x_linewidth"],
        )

    ax.set_title(
        cfg["title"],
        fontsize=PLOT_CFG["title_fontsize"],
    )

    ax.set_aspect("equal")

    _apply_axis_style(
        ax,
        case=case,
    )

    _make_legend(
        ax,
        label=cfg["legend_label"],
        add_unknown=add_unknown,
        legend_loc=cfg["legend_loc"],
    )


def _scatter_interior(
    fig: mpl.figure.Figure,
    ax: mpl.axes.Axes,
    pts: np.ndarray,
    values: np.ndarray,
    cfg: dict[str, Any],
    x_mask: np.ndarray | None = None,
    vmin: float | None = None,
    vmax: float | None = None,
    cbar_fmt: str | None = None,
    case: str | None = None,
) -> None:
    pts = np.asarray(
        pts,
        dtype=np.float64,
    )

    values = np.asarray(
        values,
        dtype=np.float64,
    ).reshape(-1)

    if pts.shape[0] != values.shape[0]:
        raise ValueError(
            "Interior coordinates and values have different lengths"
        )

    valid = np.isfinite(values)

    if not np.any(valid):
        raise ValueError(
            "No finite interior values are available for plotting"
        )

    scatter = ax.scatter(
        pts[valid, 0],
        pts[valid, 1],
        c=values[valid],
        s=PLOT_CFG["interior_marker_size"],
        cmap=cfg["cmap"],
        vmin=vmin,
        vmax=vmax,
        linewidths=0.0,
    )

    if cfg.get("show_colorbar", True):
        _add_colorbar(
            fig,
            ax,
            scatter,
            fmt=cbar_fmt,
        )

    add_unknown = False

    if (
        cfg.get("show_red_x", True)
        and x_mask is not None
        and np.any(x_mask)
    ):
        x_mask = np.asarray(
            x_mask,
            dtype=bool,
        ).reshape(-1)

        if x_mask.shape[0] != pts.shape[0]:
            raise ValueError(
                "Interior highlight mask has an invalid length"
            )

        add_unknown = True

        ax.scatter(
            pts[x_mask, 0],
            pts[x_mask, 1],
            s=PLOT_CFG["unknown_x_size"],
            c=PLOT_CFG["unknown_color"],
            marker="x",
            linewidths=PLOT_CFG["unknown_x_linewidth"],
        )

    ax.set_title(
        cfg["title"],
        fontsize=PLOT_CFG["title_fontsize"],
    )

    ax.set_aspect("equal")

    _apply_axis_style(
        ax,
        case=case,
    )

    _make_legend(
        ax,
        label=cfg["legend_label"],
        add_unknown=add_unknown,
        legend_loc=cfg["legend_loc"],
    )


def _imshow_grid(
    fig: mpl.figure.Figure,
    ax: mpl.axes.Axes,
    grid: np.ndarray,
    cfg: dict[str, Any],
    x_mask: np.ndarray | None = None,
    case: str | None = None,
) -> None:
    image = ax.imshow(
        grid,
        origin="lower",
        cmap=cfg["cmap"],
    )

    if cfg.get("show_colorbar", True):
        _add_colorbar(
            fig,
            ax,
            image,
        )

    add_unknown = False

    if (
        cfg.get("show_red_x", True)
        and x_mask is not None
        and np.any(x_mask)
    ):
        add_unknown = True

        yy, xx = np.where(x_mask)

        ax.scatter(
            xx,
            yy,
            s=PLOT_CFG["unknown_x_size"],
            c=PLOT_CFG["unknown_color"],
            marker="x",
            linewidths=PLOT_CFG["unknown_x_linewidth"],
        )

    ax.set_title(
        cfg["title"],
        fontsize=PLOT_CFG["title_fontsize"],
    )

    ax.set_aspect("equal")

    _apply_axis_style(
        ax,
        case=case,
    )

    _make_legend(
        ax,
        label=cfg["legend_label"],
        add_unknown=add_unknown,
        legend_loc=cfg["legend_loc"],
    )


def _save_png_svg(
    fig: mpl.figure.Figure,
    out_path_no_ext: Path,
) -> None:
    fig.savefig(
        str(out_path_no_ext) + ".png",
        dpi=PLOT_CFG["dpi_png"],
        bbox_inches="tight",
    )

    fig.savefig(
        str(out_path_no_ext) + ".svg",
        bbox_inches="tight",
    )


# =========================================================
# Checkpoint utilities
# =========================================================

def load_checkpoint(
    checkpoint_path: Path,
    device: torch.device,
) -> dict[str, Any]:
    if not checkpoint_path.exists():
        raise FileNotFoundError(
            f"Checkpoint not found: {checkpoint_path}"
        )

    # weights_only was added in newer PyTorch versions.
    try:
        checkpoint = torch.load(
            checkpoint_path,
            map_location=device,
            weights_only=False,
        )
    except TypeError:
        checkpoint = torch.load(
            checkpoint_path,
            map_location=device,
        )

    if not isinstance(checkpoint, dict):
        raise TypeError(
            "The checkpoint must contain a dictionary"
        )

    required_keys = {
        "in_dim",
        "hidden_dim",
        "model_state",
    }

    missing_keys = (
        required_keys
        - set(checkpoint.keys())
    )

    if missing_keys:
        raise KeyError(
            "Checkpoint is missing required keys: "
            + ", ".join(sorted(missing_keys))
        )

    return checkpoint


def build_model_from_checkpoint(
    checkpoint: dict[str, Any],
    sample: Any,
    case: str,
    device: torch.device,
) -> FluxGNN:
    checkpoint_case = checkpoint.get("case")

    if (
        checkpoint_case is not None
        and checkpoint_case != case
    ):
        raise ValueError(
            f"Checkpoint case '{checkpoint_case}' does not match "
            f"requested case '{case}'"
        )

    if sample.x.ndim != 2:
        raise ValueError(
            f"sample.x must have shape [N, F], "
            f"but received {tuple(sample.x.shape)}"
        )

    sample_in_dim = int(
        sample.x.shape[-1]
    )

    checkpoint_in_dim = int(
        checkpoint["in_dim"]
    )

    if sample_in_dim != checkpoint_in_dim:
        raise ValueError(
            f"Dataset input dimension {sample_in_dim} does not match "
            f"checkpoint input dimension {checkpoint_in_dim}"
        )

    hidden_dim = int(
        checkpoint["hidden_dim"]
    )

    latent_dim = int(
        checkpoint.get("latent_dim", 32)
    )

    dropout = float(
        checkpoint.get("dropout", 0.0)
    )

    model = FluxGNN(
        in_dim=checkpoint_in_dim,
        hidden_dim=hidden_dim,
        latent_dim=latent_dim,
        dropout=dropout,
    ).to(device)

    model.load_state_dict(
        checkpoint["model_state"],
        strict=True,
    )

    model.eval()

    return model


# =========================================================
# Main test function
# =========================================================

def run_test(
    data_dir: str | Path,
    case: str,
    ckpt_path: str | Path,
    out_dir: str | Path,
    sample_idx: int = 0,
    quad_res: int = 121,
) -> None:
    data_dir = Path(data_dir)
    ckpt_path = Path(ckpt_path)
    out_dir = Path(out_dir)

    if quad_res <= 0:
        raise ValueError(
            "quad_res must be greater than zero"
        )

    out_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    print(f"Using device: {device}")

    dataset = BoundaryFluxDataset(
        data_dir,
        split="test",
        full_load=True,
    )

    if len(dataset) == 0:
        raise ValueError(
            "The test dataset is empty"
        )

    if sample_idx < 0 or sample_idx >= len(dataset):
        raise IndexError(
            f"sample_idx={sample_idx} is outside the valid range "
            f"[0, {len(dataset) - 1}]"
        )

    sample = dataset.get(sample_idx)

    if not hasattr(sample, "x"):
        raise AttributeError(
            "The test sample does not contain x"
        )

    if not hasattr(sample, "edge_index"):
        raise AttributeError(
            "The test sample does not contain edge_index"
        )

    if not hasattr(sample, "y"):
        raise AttributeError(
            "The test sample does not contain y"
        )

    checkpoint = load_checkpoint(
        ckpt_path,
        device,
    )

    model = build_model_from_checkpoint(
        checkpoint,
        sample,
        case,
        device,
    )

    # The model only needs x and edge_index, so the Data object
    # can be sent directly to the selected device.
    data = sample.clone().to(device)

    with torch.inference_mode():
        output = model(data)

    q_pred = _to_numpy(
        output.q_pred,
        dtype=np.float64,
        flatten=True,
    )

    q_true = _to_numpy(
        sample.y,
        dtype=np.float64,
        flatten=True,
    )

    _validate_same_shape(
        "q_pred",
        q_pred,
        "q_true",
        q_true,
    )

    _check_finite(
        "q_pred",
        q_pred,
    )

    _check_finite(
        "q_true",
        q_true,
    )

    # -----------------------------------------------------
    # Boundary geometry and prescribed data
    # -----------------------------------------------------

    boundary_coords = _to_numpy(
        sample.coords,
        dtype=np.float64,
    )

    boundary_normals = _to_numpy(
        sample.normals,
        dtype=np.float64,
    )

    boundary_ds = _to_numpy(
        sample.ds,
        dtype=np.float64,
        flatten=True,
    )

    u_bc = _to_numpy(
        sample.u_bc,
        dtype=np.float64,
        flatten=True,
    )

    if (
        boundary_coords.ndim != 2
        or boundary_coords.shape[1] != 2
    ):
        raise ValueError(
            "sample.coords must have shape [N, 2]"
        )

    if (
        boundary_normals.ndim != 2
        or boundary_normals.shape != boundary_coords.shape
    ):
        raise ValueError(
            "sample.normals must have the same shape as sample.coords"
        )

    num_boundary_nodes = int(
        boundary_coords.shape[0]
    )

    boundary_ds = _validate_node_array(
        "boundary_ds",
        boundary_ds,
        num_boundary_nodes,
    )

    u_bc = _validate_node_array(
        "u_bc",
        u_bc,
        num_boundary_nodes,
    )

    q_pred = _validate_node_array(
        "q_pred",
        q_pred,
        num_boundary_nodes,
    )

    q_true = _validate_node_array(
        "q_true",
        q_true,
        num_boundary_nodes,
    )

    _check_finite(
        "boundary_coords",
        boundary_coords,
    )

    _check_finite(
        "boundary_normals",
        boundary_normals,
    )

    # -----------------------------------------------------
    # Source-term function
    # -----------------------------------------------------

    params = _to_numpy(
        sample.params,
        dtype=np.float64,
        flatten=True,
    )

    f_fn = build_problem_from_params(
        case,
        params,
    )

    # -----------------------------------------------------
    # BEM boundary solution
    # -----------------------------------------------------

    domain_quad = make_domain_quadrature(
        sample.geometry_type,
        resolution=quad_res,
    )

    cache = BEMCache.build(
        boundary_coords=boundary_coords,
        boundary_normals=boundary_normals,
        boundary_ds=boundary_ds,
        domain_quad=domain_quad,
    )

    q_bem = solve_flux_collocation_cached(
        cache,
        u_bc,
        f_fn,
    )

    q_bem = _validate_node_array(
        "q_bem",
        q_bem,
        num_boundary_nodes,
    )

    # -----------------------------------------------------
    # Interior evaluation points
    # -----------------------------------------------------

    all_points = _to_numpy(
        sample.domain_points,
        dtype=np.float64,
    )

    domain_mask = _to_numpy(
        sample.domain_mask,
        flatten=True,
    ).astype(bool)

    if (
        all_points.ndim != 2
        or all_points.shape[1] != 2
    ):
        raise ValueError(
            "sample.domain_points must have shape [M, 2]"
        )

    if domain_mask.shape[0] != all_points.shape[0]:
        raise ValueError(
            "domain_mask length does not match domain_points"
        )

    if not np.any(domain_mask):
        raise ValueError(
            "The domain mask does not contain any interior points"
        )

    interior_points = all_points[domain_mask]

    # -----------------------------------------------------
    # Interior field reconstructed from network prediction
    # -----------------------------------------------------

    u_pred_interior = evaluate_field(
        eval_pts=interior_points,
        boundary_coords=boundary_coords,
        boundary_normals=boundary_normals,
        boundary_ds=boundary_ds,
        u_bc=u_bc,
        q_bc=q_pred,
        f_fn=f_fn,
        domain_quad=domain_quad,
    )

    u_pred_interior = np.asarray(
        u_pred_interior,
        dtype=np.float64,
    ).reshape(-1)

    # -----------------------------------------------------
    # Interior field reconstructed from the BEM-solved flux
    # -----------------------------------------------------

    u_bem_interior = evaluate_field(
        eval_pts=interior_points,
        boundary_coords=boundary_coords,
        boundary_normals=boundary_normals,
        boundary_ds=boundary_ds,
        u_bc=u_bc,
        q_bc=q_bem,
        f_fn=f_fn,
        domain_quad=domain_quad,
    )

    u_bem_interior = np.asarray(
        u_bem_interior,
        dtype=np.float64,
    ).reshape(-1)

    if (
        u_pred_interior.shape[0]
        != interior_points.shape[0]
    ):
        raise ValueError(
            "evaluate_field returned an unexpected number of "
            "predicted interior values"
        )

    if (
        u_bem_interior.shape[0]
        != interior_points.shape[0]
    ):
        raise ValueError(
            "evaluate_field returned an unexpected number of "
            "BEM interior values"
        )

    _check_finite(
        "u_pred_interior",
        u_pred_interior,
    )

    _check_finite(
        "u_bem_interior",
        u_bem_interior,
    )

    # -----------------------------------------------------
    # Complete-domain arrays
    # -----------------------------------------------------

    full_pred = np.full(
        (all_points.shape[0],),
        np.nan,
        dtype=np.float64,
    )

    full_bem = np.full(
        (all_points.shape[0],),
        np.nan,
        dtype=np.float64,
    )

    full_exact = _to_numpy(
        sample.u_domain_exact,
        dtype=np.float64,
        flatten=True,
    )

    if full_exact.shape[0] != all_points.shape[0]:
        raise ValueError(
            "u_domain_exact length does not match domain_points"
        )

    full_pred[domain_mask] = u_pred_interior
    full_bem[domain_mask] = u_bem_interior

    exact_interior = full_exact[domain_mask]

    _check_finite(
        "exact_interior",
        exact_interior,
    )

    # -----------------------------------------------------
    # Grid representation
    # -----------------------------------------------------

    domain_shape_values = _to_numpy(
        sample.domain_shape,
        flatten=True,
    )

    shape = tuple(
        int(value)
        for value in domain_shape_values
    )

    if len(shape) != 2:
        raise ValueError(
            f"domain_shape must contain two dimensions, received {shape}"
        )

    if int(np.prod(shape)) != all_points.shape[0]:
        raise ValueError(
            f"domain_shape={shape} contains {int(np.prod(shape))} entries, "
            f"but domain_points contains {all_points.shape[0]} points"
        )

    pred_grid = full_pred.reshape(shape)
    bem_grid = full_bem.reshape(shape)
    exact_grid = full_exact.reshape(shape)
    err_grid = pred_grid - exact_grid

    pred_values = full_pred[domain_mask]
    bem_values = full_bem[domain_mask]
    exact_values = full_exact[domain_mask]
    error_values = pred_values - exact_values

    # -----------------------------------------------------
    # Error metrics
    # -----------------------------------------------------

    q_metrics = compute_error_metrics(
        q_pred,
        q_true,
    )

    u_metrics = compute_error_metrics(
        pred_values,
        exact_values,
    )

    q_bem_metrics = compute_error_metrics(
        q_bem,
        q_true,
    )

    u_bem_metrics = compute_error_metrics(
        bem_values,
        exact_values,
    )

    q_error = q_pred - q_true

    # -----------------------------------------------------
    # Shared color ranges
    # -----------------------------------------------------

    u_bc_rounded = np.round(
        u_bc,
        decimals=4,
    )

    boundary_u_vmin, boundary_u_vmax = _finite_minmax(
        u_bc_rounded
    )

    q_vmin, q_vmax = _finite_minmax(
        q_pred,
        q_true,
    )

    u_vmin, u_vmax = _finite_minmax(
        pred_values,
        exact_values,
        bem_values,
    )

    q_error_limit = _symmetric_limit(
        q_error
    )

    u_error_limit = _symmetric_limit(
        error_values
    )

    # -----------------------------------------------------
    # Highlight masks
    # -----------------------------------------------------

    xmask_known_u = build_boundary_x_mask(
        SUBPLOT_CFG["known_u"]["x_mode"],
        boundary_coords,
        q_err=q_error,
    )

    xmask_pred_q = build_boundary_x_mask(
        SUBPLOT_CFG["pred_q"]["x_mode"],
        boundary_coords,
        q_err=q_error,
    )

    xmask_true_q = build_boundary_x_mask(
        SUBPLOT_CFG["true_q"]["x_mode"],
        boundary_coords,
        q_err=q_error,
    )

    xmask_q_err = build_boundary_x_mask(
        SUBPLOT_CFG["q_err"]["x_mode"],
        boundary_coords,
        q_err=q_error,
    )

    xmask_pred_u = build_interior_x_mask(
        SUBPLOT_CFG["pred_u"]["x_mode"],
        u_err=error_values,
    )

    xmask_true_u = build_interior_x_mask(
        SUBPLOT_CFG["true_u"]["x_mode"],
        u_err=error_values,
    )

    xmask_u_err = build_interior_x_mask(
        SUBPLOT_CFG["u_err"]["x_mode"],
        u_err=error_values,
    )

    xmask_bem_u = build_interior_x_mask(
        SUBPLOT_CFG["bem_u"]["x_mode"],
        u_err=error_values,
    )

    # -----------------------------------------------------
    # Main comparison figure
    # -----------------------------------------------------

    fig, axes = plt.subplots(
        2,
        3,
        figsize=PLOT_CFG["figsize_main"],
    )

    axes = axes.ravel()

    _scatter_boundary(
        fig=fig,
        ax=axes[0],
        coords=boundary_coords,
        values=u_bc,
        cfg=SUBPLOT_CFG["known_u"],
        x_mask=xmask_known_u,
        vmin=boundary_u_vmin,
        vmax=boundary_u_vmax,
        cbar_fmt="%.4f",
        case=case,
    )

    _scatter_boundary(
        fig=fig,
        ax=axes[1],
        coords=boundary_coords,
        values=q_pred,
        cfg=SUBPLOT_CFG["pred_q"],
        x_mask=xmask_pred_q,
        vmin=q_vmin,
        vmax=q_vmax,
        case=case,
    )

    _scatter_boundary(
        fig=fig,
        ax=axes[2],
        coords=boundary_coords,
        values=q_true,
        cfg=SUBPLOT_CFG["true_q"],
        x_mask=xmask_true_q,
        vmin=q_vmin,
        vmax=q_vmax,
        case=case,
    )

    _scatter_interior(
        fig=fig,
        ax=axes[3],
        pts=interior_points,
        values=pred_values,
        cfg=SUBPLOT_CFG["pred_u"],
        x_mask=xmask_pred_u,
        vmin=u_vmin,
        vmax=u_vmax,
        case=case,
    )

    _scatter_interior(
        fig=fig,
        ax=axes[4],
        pts=interior_points,
        values=exact_values,
        cfg=SUBPLOT_CFG["true_u"],
        x_mask=xmask_true_u,
        vmin=u_vmin,
        vmax=u_vmax,
        case=case,
    )

    _scatter_interior(
        fig=fig,
        ax=axes[5],
        pts=interior_points,
        values=error_values,
        cfg=SUBPLOT_CFG["u_err"],
        x_mask=xmask_u_err,
        vmin=-u_error_limit,
        vmax=u_error_limit,
        case=case,
    )

    fig.tight_layout()

    main_output_base = (
        out_dir
        / f"sample_{sample_idx:04d}_comparison"
    )

    _save_png_svg(
        fig,
        main_output_base,
    )

    plt.close(fig)

    # -----------------------------------------------------
    # Additional comparison figure
    # -----------------------------------------------------

    fig_extra, axes_extra = plt.subplots(
        1,
        2,
        figsize=PLOT_CFG["figsize_extra"],
    )

    _scatter_boundary(
        fig=fig_extra,
        ax=axes_extra[0],
        coords=boundary_coords,
        values=q_error,
        cfg=SUBPLOT_CFG["q_err"],
        x_mask=xmask_q_err,
        vmin=-q_error_limit,
        vmax=q_error_limit,
        case=case,
    )

    _scatter_interior(
        fig=fig_extra,
        ax=axes_extra[1],
        pts=interior_points,
        values=bem_values,
        cfg=SUBPLOT_CFG["bem_u"],
        x_mask=xmask_bem_u,
        vmin=u_vmin,
        vmax=u_vmax,
        case=case,
    )

    fig_extra.tight_layout()

    extra_output_base = (
        out_dir
        / f"sample_{sample_idx:04d}_extra"
    )

    _save_png_svg(
        fig_extra,
        extra_output_base,
    )

    plt.close(fig_extra)

    # -----------------------------------------------------
    # Save numerical results
    # -----------------------------------------------------

    npz_path = (
        out_dir
        / f"sample_{sample_idx:04d}_outputs.npz"
    )

    np.savez_compressed(
        npz_path,

        boundary_coords=boundary_coords,
        boundary_normals=boundary_normals,
        boundary_ds=boundary_ds,

        u_boundary_known=u_bc,

        q_pred=q_pred,
        q_true=q_true,
        q_bem=q_bem,
        q_error=q_error,

        domain_points=all_points,
        domain_mask=domain_mask,

        u_pred_domain=full_pred,
        u_bem_domain=full_bem,
        u_exact_domain=full_exact,

        pred_grid=pred_grid,
        bem_grid=bem_grid,
        exact_grid=exact_grid,
        err_grid=err_grid,

        q_mse=q_metrics["mse"],
        q_rmse=q_metrics["rmse"],
        q_mae=q_metrics["mae"],
        q_max_abs=q_metrics["max_abs"],
        q_relative_l2=q_metrics["relative_l2"],
        q_normalized_max_abs=q_metrics["normalized_max_abs"],

        u_mse=u_metrics["mse"],
        u_rmse=u_metrics["rmse"],
        u_mae=u_metrics["mae"],
        u_max_abs=u_metrics["max_abs"],
        u_relative_l2=u_metrics["relative_l2"],
        u_normalized_max_abs=u_metrics["normalized_max_abs"],

        q_bem_mse=q_bem_metrics["mse"],
        u_bem_mse=u_bem_metrics["mse"],

        parameters=params,
    )

    # -----------------------------------------------------
    # Save summary
    # -----------------------------------------------------

    main_png_path = Path(
        str(main_output_base) + ".png"
    ).resolve()

    main_svg_path = Path(
        str(main_output_base) + ".svg"
    ).resolve()

    extra_png_path = Path(
        str(extra_output_base) + ".png"
    ).resolve()

    extra_svg_path = Path(
        str(extra_output_base) + ".svg"
    ).resolve()

    summary = {
        "sample_idx": int(sample_idx),
        "case": case,
        "device": str(device),

        "checkpoint": str(
            ckpt_path.resolve()
        ),
        "checkpoint_epoch": int(
            checkpoint.get("epoch", -1)
        ),

        "model": {
            "in_dim": int(checkpoint["in_dim"]),
            "hidden_dim": int(checkpoint["hidden_dim"]),
            "latent_dim": int(
                checkpoint.get("latent_dim", 32)
            ),
            "dropout": float(
                checkpoint.get("dropout", 0.0)
            ),
            "beta": float(
                checkpoint.get("beta", 1e-3)
            ),
        },

        "parameters": [
            float(value)
            for value in params
        ],

        "boundary_prediction_metrics": q_metrics,
        "interior_reconstruction_metrics": u_metrics,

        "bem_boundary_metrics": q_bem_metrics,
        "bem_interior_metrics": u_bem_metrics,

        "saved_files": {
            "main_png": str(main_png_path),
            "main_svg": str(main_svg_path),
            "extra_png": str(extra_png_path),
            "extra_svg": str(extra_svg_path),
            "numerical_outputs": str(
                npz_path.resolve()
            ),
        },
    }

    summary_path = (
        out_dir
        / f"sample_{sample_idx:04d}_summary.json"
    )

    with summary_path.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            summary,
            file,
            ensure_ascii=False,
            indent=2,
            allow_nan=True,
        )

    # -----------------------------------------------------
    # Console output
    # -----------------------------------------------------

    print()
    print("Test completed successfully.")
    print(f"Sample index: {sample_idx}")
    print(f"Case: {case}")
    print(
        f"Checkpoint epoch: "
        f"{checkpoint.get('epoch', 'unknown')}"
    )

    print()
    print("Boundary Neumann prediction:")
    print(
        f"  MSE          = "
        f"{q_metrics['mse']:.6e}"
    )
    print(
        f"  RMSE         = "
        f"{q_metrics['rmse']:.6e}"
    )
    print(
        f"  MAE          = "
        f"{q_metrics['mae']:.6e}"
    )
    print(
        f"  Max abs      = "
        f"{q_metrics['max_abs']:.6e}"
    )
    print(
        f"  Relative L2  = "
        f"{q_metrics['relative_l2']:.6e}"
    )

    print()
    print("Interior field reconstruction:")
    print(
        f"  MSE          = "
        f"{u_metrics['mse']:.6e}"
    )
    print(
        f"  RMSE         = "
        f"{u_metrics['rmse']:.6e}"
    )
    print(
        f"  MAE          = "
        f"{u_metrics['mae']:.6e}"
    )
    print(
        f"  Max abs      = "
        f"{u_metrics['max_abs']:.6e}"
    )
    print(
        f"  Relative L2  = "
        f"{u_metrics['relative_l2']:.6e}"
    )

    print()
    print(f"Saved test outputs to: {out_dir.resolve()}")


# =========================================================
# Command-line interface
# =========================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate the trained full-graph attention model "
            "and reconstruct the interior field using BEM."
        )
    )

    parser.add_argument(
        "--data_dir",
        type=Path,
        default=Path(
            DEFAULT_CONFIG["data_dir"]
        ),
    )

    parser.add_argument(
        "--case",
        type=str,
        choices=[
            "case1",
            "case2",
            "case3",
        ],
        default=DEFAULT_CONFIG["case"],
    )

    parser.add_argument(
        "--ckpt",
        type=Path,
        default=Path(
            DEFAULT_CONFIG["ckpt"]
        ),
    )

    parser.add_argument(
        "--out_dir",
        type=Path,
        default=Path(
            DEFAULT_CONFIG["out_dir"]
        ),
    )

    parser.add_argument(
        "--sample_idx",
        type=int,
        default=DEFAULT_CONFIG["sample_idx"],
    )

    parser.add_argument(
        "--quad_res",
        type=int,
        default=DEFAULT_CONFIG["quad_res"],
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    run_test(
        data_dir=args.data_dir,
        case=args.case,
        ckpt_path=args.ckpt,
        out_dir=args.out_dir,
        sample_idx=args.sample_idx,
        quad_res=args.quad_res,
    )


if __name__ == "__main__":
    main()
